name: 'Send Teams Message'
description: 'Send messages to Teams channel via webhook using Teams cards'

inputs:
  webhook-url:
    description: 'The Teams webhook URL'
    required: true
  message-title:
    description: 'The title of the message'
    required: true
  message-text:
    description: 'The text of the message'
    required: true
  message-type:
    description: 'Set this input the job.status, Should be one of failed, cancelled, or success. Default is information'
    required: false
    default: 'information' #'0076D7'
  workflow-url:
    description: 'The URL of the workflow'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set theme color
      id: theme-color
      shell: bash
      run: |
        msg_type=$(echo "${{ inputs.message-type }}" | tr '[:upper:]' '[:lower:]')
        case "$msg_type" in
          information)
            echo "themeColor=0076D7" >> $GITHUB_OUTPUT
            ;;
          cancelled)
            echo "themeColor=FF355A" >> $GITHUB_OUTPUT
            ;;
          failure)
            echo "themeColor=FF0000" >> $GITHUB_OUTPUT
            ;;
          success)
            echo "themeColor=008000" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "themeColor=0076D7" >> $GITHUB_OUTPUT
            ;;
        esac

    - name: Send message to Teams
      shell: bash
      run: |
        curl -H 'Content-Type: application/json' -d '{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "summary": "${{ inputs.message-title }}",
          "themeColor": "${{ steps.theme-color.outputs.themeColor }}",
          "title": "${{ inputs.message-title }}",
          "text": "${{ inputs.message-text }}",
          "potentialAction": [
            {
              "@type": "OpenUri",
              "name": "View in GitHub",
              "targets": [
                { "os": "default", "uri": "${{ inputs.workflow-url }}" }
              ]
            }
          ]
        }' ${{ inputs.webhook-url }}